### ISSUE TITLE
Generate static binary

### ISSUE THREAD

**Issue by srikanth007m** [ArchiDroid/haveged#1]
How to generate haveged static binary ? 
./configure --enable-static=yes  CC=arm-linux-gnueabi-gcc --host=arm-linux --target=arm-linux CFLAGS="-static"
Still i am getting dynamically linked binary
haveged: ELF 32-bit LSB  executable, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=b6b59fa8398fc722121b1c00586561ab2e7dd59d, not stripped

Am i doing wrong?

**Comment by srikanth007m** [comment]
i figured it out. Thanks.

**Comment by JustArchi** [comment]
Consider using my cc.sh - https://dl.dropboxusercontent.com/u/23869279/Files/cc.sh

`source cc.sh`

Then in haveged dir:
`./configure $CONFIGANDROID`

Then `make`

If you need more help, I suggest reading my cross compiling guide - http://forum.xda-developers.com/showthread.php?t=2723240
